#define USE_LED_BUILTIN
#define SERIALCOM_BAUD 1000000

enum IN_COM_IDs
{
	ID_UPTIME_REQUEST = 1,
	ID_PIN_CONTROL
};

enum OUT_COM_IDs
{
	ID_UPTIME = 1,
	ID_PIN_CONTROL_OUT
};

enum PIN_CONTROL_INDICES
{
	PIN_CONTROLLER_MODE_SELECT,
	PIN_SELECT,
	PIN_CONTROL_VALUE_BYTES
};

enum PIN_CONTROLLER_MODES
{
	MODE_PINMODE,
	MODE_DIGITALREAD,
	MODE_DIGITALWRITE,
	MODE_ANALOGREAD,
	MODE_ANALOGWRITE
};

const /*constexpr*/ byte INCOMIDSIZES[3] = {0, 1, 4};
const /*constexpr*/ byte OUTCOMIDSIZES[3] = { 0, 4, 3 };